create table `emailmql` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `project_name`  VARCHAR(255) NOT NULL,
  `customer_name` VARCHAR(20) NOT NULL,
  `customer_phone` VARCHAR(20) NOT NULL,
  `wg_amt` VARCHAR(10) NOT NULL,
  `brands` VARCHAR(50) NOT NULL,
  `product_category` VARCHAR(20) NOT NULL,
  `country` VARCHAR(10) NOT NULL,
  `state` VARCHAR(10) NOT NULL,
  `city` VARCHAR(10) NOT NULL,
  `lead_source1` VARCHAR(10) NOT NULL,
  `mail_to` VARCHAR(255) NOT NULL,
  `project_desp` VARCHAR(255) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `oppty_number` VARCHAR(20),
  `feedback` VARCHAR(255),
  `amount_cny` DOUBLE,
  PRIMARY KEY (`id`)
);
